name: Exploring Workflow Dispatch Trigger

on:
  workflow_dispatch:
    inputs:
      description: Run Specific Job
      required: false
      default: 'warning'
       type: boolean
        
  
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:

      - run: echo "Exploring Workflow Dispatch Trigger"
